/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as MuseeRouteImport } from './routes/musee'
import { Route as LiveRouteImport } from './routes/live'
import { Route as HistoireRouteImport } from './routes/histoire'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as AthletesRouteImport } from './routes/athletes'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosIdRouteImport } from './routes/videos.$id'
import { Route as PodcastIdRouteImport } from './routes/podcast.$id'
import { Route as HistoireIdRouteImport } from './routes/histoire.$id'
import { Route as AthletesIdRouteImport } from './routes/athletes.$id'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const MuseeRoute = MuseeRouteImport.update({
  id: '/musee',
  path: '/musee',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoireRoute = HistoireRouteImport.update({
  id: '/histoire',
  path: '/histoire',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesRoute = AthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIdRoute = VideosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VideosRoute,
} as any)
const PodcastIdRoute = PodcastIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PodcastRoute,
} as any)
const HistoireIdRoute = HistoireIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HistoireRoute,
} as any)
const AthletesIdRoute = AthletesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AthletesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/athletes': typeof AthletesRouteWithChildren
  '/carte': typeof CarteRoute
  '/histoire': typeof HistoireRouteWithChildren
  '/live': typeof LiveRoute
  '/musee': typeof MuseeRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/videos': typeof VideosRouteWithChildren
  '/athletes/$id': typeof AthletesIdRoute
  '/histoire/$id': typeof HistoireIdRoute
  '/podcast/$id': typeof PodcastIdRoute
  '/videos/$id': typeof VideosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/athletes': typeof AthletesRouteWithChildren
  '/carte': typeof CarteRoute
  '/histoire': typeof HistoireRouteWithChildren
  '/live': typeof LiveRoute
  '/musee': typeof MuseeRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/videos': typeof VideosRouteWithChildren
  '/athletes/$id': typeof AthletesIdRoute
  '/histoire/$id': typeof HistoireIdRoute
  '/podcast/$id': typeof PodcastIdRoute
  '/videos/$id': typeof VideosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/athletes': typeof AthletesRouteWithChildren
  '/carte': typeof CarteRoute
  '/histoire': typeof HistoireRouteWithChildren
  '/live': typeof LiveRoute
  '/musee': typeof MuseeRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/videos': typeof VideosRouteWithChildren
  '/athletes/$id': typeof AthletesIdRoute
  '/histoire/$id': typeof HistoireIdRoute
  '/podcast/$id': typeof PodcastIdRoute
  '/videos/$id': typeof VideosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/athletes'
    | '/carte'
    | '/histoire'
    | '/live'
    | '/musee'
    | '/podcast'
    | '/videos'
    | '/athletes/$id'
    | '/histoire/$id'
    | '/podcast/$id'
    | '/videos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/athletes'
    | '/carte'
    | '/histoire'
    | '/live'
    | '/musee'
    | '/podcast'
    | '/videos'
    | '/athletes/$id'
    | '/histoire/$id'
    | '/podcast/$id'
    | '/videos/$id'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/athletes'
    | '/carte'
    | '/histoire'
    | '/live'
    | '/musee'
    | '/podcast'
    | '/videos'
    | '/athletes/$id'
    | '/histoire/$id'
    | '/podcast/$id'
    | '/videos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  AthletesRoute: typeof AthletesRouteWithChildren
  CarteRoute: typeof CarteRoute
  HistoireRoute: typeof HistoireRouteWithChildren
  LiveRoute: typeof LiveRoute
  MuseeRoute: typeof MuseeRoute
  PodcastRoute: typeof PodcastRouteWithChildren
  VideosRoute: typeof VideosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musee': {
      id: '/musee'
      path: '/musee'
      fullPath: '/musee'
      preLoaderRoute: typeof MuseeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/histoire': {
      id: '/histoire'
      path: '/histoire'
      fullPath: '/histoire'
      preLoaderRoute: typeof HistoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes': {
      id: '/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof AthletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$id': {
      id: '/videos/$id'
      path: '/$id'
      fullPath: '/videos/$id'
      preLoaderRoute: typeof VideosIdRouteImport
      parentRoute: typeof VideosRoute
    }
    '/podcast/$id': {
      id: '/podcast/$id'
      path: '/$id'
      fullPath: '/podcast/$id'
      preLoaderRoute: typeof PodcastIdRouteImport
      parentRoute: typeof PodcastRoute
    }
    '/histoire/$id': {
      id: '/histoire/$id'
      path: '/$id'
      fullPath: '/histoire/$id'
      preLoaderRoute: typeof HistoireIdRouteImport
      parentRoute: typeof HistoireRoute
    }
    '/athletes/$id': {
      id: '/athletes/$id'
      path: '/$id'
      fullPath: '/athletes/$id'
      preLoaderRoute: typeof AthletesIdRouteImport
      parentRoute: typeof AthletesRoute
    }
  }
}

interface AthletesRouteChildren {
  AthletesIdRoute: typeof AthletesIdRoute
}

const AthletesRouteChildren: AthletesRouteChildren = {
  AthletesIdRoute: AthletesIdRoute,
}

const AthletesRouteWithChildren = AthletesRoute._addFileChildren(
  AthletesRouteChildren,
)

interface HistoireRouteChildren {
  HistoireIdRoute: typeof HistoireIdRoute
}

const HistoireRouteChildren: HistoireRouteChildren = {
  HistoireIdRoute: HistoireIdRoute,
}

const HistoireRouteWithChildren = HistoireRoute._addFileChildren(
  HistoireRouteChildren,
)

interface PodcastRouteChildren {
  PodcastIdRoute: typeof PodcastIdRoute
}

const PodcastRouteChildren: PodcastRouteChildren = {
  PodcastIdRoute: PodcastIdRoute,
}

const PodcastRouteWithChildren =
  PodcastRoute._addFileChildren(PodcastRouteChildren)

interface VideosRouteChildren {
  VideosIdRoute: typeof VideosIdRoute
}

const VideosRouteChildren: VideosRouteChildren = {
  VideosIdRoute: VideosIdRoute,
}

const VideosRouteWithChildren =
  VideosRoute._addFileChildren(VideosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  AthletesRoute: AthletesRouteWithChildren,
  CarteRoute: CarteRoute,
  HistoireRoute: HistoireRouteWithChildren,
  LiveRoute: LiveRoute,
  MuseeRoute: MuseeRoute,
  PodcastRoute: PodcastRouteWithChildren,
  VideosRoute: VideosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
